/*
 * <copyright file="DefaultClassExtension.cs" company="Lifeprojects.de">
 *     Class: DefaultClassExtension
 *     Copyright © Lifeprojects.de 2026
 * </copyright>
 *
 * <author>Gerhard Ahrens - Lifeprojects.de</author>
 * <email>gerhard.ahrens@lifeprojects.de</email>
 * <date>20.07.2025 14:08:20</date>
 * <Project>EasyPrototypingNET</Project>
 *
 * <summary>
 * Die Klasse DefaultClassExtension stellt per CodeDOM einen SorceGenerator für Klassen zur Verfügung.
 * </summary>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by the Free Software Foundation, 
 * either version 3 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful,but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.You should have received a copy of the GNU General Public License along with this program. 
 * If not, see <http://www.gnu.org/licenses/>.
*/

namespace Console.CustomDataTable
{
    using System;
    using System.CodeDom;
    using System.CodeDom.Compiler;
    //using System.Data;

    using Microsoft.CSharp;

    public static class DefaultClassExtension
    {

        public static string DefaultClassToCode(this string self)
        {
            string className = self;
            if (string.IsNullOrWhiteSpace(className) == true)
            { 
                className = "UnnamedTableAsClass";
            }

            className = $"{className}";

            // Create the class
            CodeTypeDeclaration codeClass = CreateClass(className);

            // Add Class to Namespace
            string namespaceName = "AutoGeneratedModel";
            CodeNamespace codeNamespace = new CodeNamespace(namespaceName);
            codeNamespace.Types.Add(codeClass);

            // Add Methode ToString()
            codeClass.Members.Add(CreateMethode("ToString", new CodeTypeReference(typeof(string)), MemberAttributes.Public | MemberAttributes.Override));

            // Add Methode GetInfo()
            codeClass.Members.Add(CreateMethode("GetInfo1", new CodeTypeReference(typeof(string))));

            codeClass.Members.Add(CreateMethode2("GetInfo2", new CodeTypeReference("ResultInfo")));

            // Generate code
            string filename = $"{namespaceName}.{className}.cs";
            CreateCodeFile(filename, codeNamespace);

            // Return filename
            return filename;
        }

        private static CodeTypeDeclaration CreateClass(string name)
        {
            CodeTypeDeclaration result = new CodeTypeDeclaration(name);
            result.Attributes = MemberAttributes.Public;
            result.IsClass = true;
            result.Members.Add(CreateConstructor(name)); // Add Klassenkonstruktor

            return result;
        }

        private static CodeConstructor CreateConstructor(string className)
        {
            CodeConstructor result = new CodeConstructor();
            result.Attributes = MemberAttributes.Public;
            result.Name = className;

            return result;
        }

        private static CodeMemberMethod CreateMethode(string methodeName, CodeTypeReference returnType, MemberAttributes attributes = MemberAttributes.Public | MemberAttributes.Final)

        {
            CodeMemberMethod resultMethod = new CodeMemberMethod();
            resultMethod.Name = methodeName;
            resultMethod.ReturnType = returnType;
            resultMethod.Attributes = attributes;
            resultMethod.Statements.Add(new CodeMethodReturnStatement(new CodePrimitiveExpression("Hallo aus der generierten Klasse")));
            return resultMethod;
        }

        private static CodeMemberMethod CreateMethode2(string methodeName, CodeTypeReference returnType, MemberAttributes attributes = MemberAttributes.Public | MemberAttributes.Final)

        {
            CodeMemberMethod resultMethod = new CodeMemberMethod();
            resultMethod.Name = methodeName;
            resultMethod.ReturnType = returnType;
            resultMethod.Attributes = attributes;

            CodeVariableDeclarationStatement varDecl = new CodeVariableDeclarationStatement("ResultInfo", "res", new CodeObjectCreateExpression("ResultInfo"));
            resultMethod.Statements.Add(varDecl);

            CodePropertyReferenceExpression propertyRef = new CodePropertyReferenceExpression(new CodeVariableReferenceExpression("res"), "Name");
            CodeAssignStatement assignStmt = new CodeAssignStatement(propertyRef, new CodePrimitiveExpression("Inhalt gefüllt via CodeDom"));
            resultMethod.Statements.Add(assignStmt);
            resultMethod.Statements.Add(new CodeMethodReturnStatement(new CodeVariableReferenceExpression("res")));

            return resultMethod;
        }

        private static void CreateCodeFile(string filename, CodeNamespace codeNamespace)
        {
            CodeGeneratorOptions codeOptions = new CodeGeneratorOptions();
            codeOptions.BlankLinesBetweenMembers = false;
            codeOptions.VerbatimOrder = true;
            codeOptions.BracingStyle = "C";
            codeOptions.IndentString = "\t";

            // Schreibe Source in File
            using (TextWriter textWriter = new StreamWriter(filename))
            {
                CSharpCodeProvider codeProvider = new CSharpCodeProvider();
                codeProvider.GenerateCodeFromNamespace(codeNamespace, textWriter, codeOptions);
            }

            // Korrektur des Autoproperty Trick (wegen Semikolon)
            string source = File.ReadAllText(filename).Replace("//;", string.Empty);
            File.WriteAllText(filename, source);
        }
    }
}
